#!/bin/sh
{
ln -sf main.conf ~/.config/sxhkd/sxhkdrc
killall sxhkd;		sxhkd &

# ~/.con/bspwm/lemonbar.sh | lemonbar &
# xfce4-panel -d &
killall polybar;	polybar frej &

# not needed if using polybar pulse module
#start-pulseaudio-x11

killall xfce-polkit;	/usr/libexec/xfce-polkit &
killall xfce4-notifyd;	/usr/lib/xfce4/notifyd/xfce4-notifyd &
killall unclutter;	unclutter -idle 2 -jitter 16 &
nitrogen --restore &
#xfsettingsd
} >/dev/null 2>&1

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config split_ratio			0.52

bspc config top_padding			26
bspc config border_width		2
bspc config window_gap			10

#bspc config single_monocle		true
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc config focus_follows_pointer	true
#bspc config pointer_follows_focus	true
bspc config pointer_follows_monitor	true
bspc config pointer_modifier		mod1

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
